#!/bin/bash

source $(dirname $0)/common.inc.sh

if [[ $1 == "--list" ]]; then
	(cd conf/; ls *.sh | sed "s/\.sh//")
	exit 1
fi

if [[ $# == 0 ]]; then
	projects=$(ls conf/*.sh)
else
	for project in $*
	do
		if [[ -f conf/${project}.sh ]]; then
			projects="$projects conf/${project}.sh"
		else
			echo "Error: project '$project' does not exist, missing configuration file conf/${project}.sh"
			exit 1
		fi
	done
fi


for project in $projects
do
	iterator=""
	repo=""
	translation_dirs=()
	subproject=()
	source $project
	import
done
