#!/bin/bash

source $(dirname $0)/common.inc.sh

if [[ $1 == "--list" ]]; then
	(cd conf/; ls *.sh | sed "s/\.sh//")
	exit 1
fi

if [[ $# == 0 ]]; then
	projects=$(ls conf/*.sh)
else
	for project in $*
	do
		projects="$projects conf/${project}.sh"
	done
fi

for project in $projects
do
	source $project
	update
done
